library/locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('signup/', views.RegisterUserView.as_view(), name= 'signup'),
]

library/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent = True)),
]

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

library/locallibrary/catalog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
from django.conf import settings

from datetime import date

class Genre(models.Model):
    '''Model representing a book genre'''
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)'
    )

    def __str__(self):
        '''String for representing the Model object'''
        return self.name
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message='Genre already exists (case insensitive match)'
            ),
        ]


class Author(models.Model):
    """Model representing the author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access this particular author instance"""
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):
    name = models.CharField(max_length=200, unique=True,help_text='Enter natural language e.g. English, Spanish etc')
    def get_absolute_url(self):
        return reverse('language-detail', args=[str(str.id)])
    
    def __str__(self):
        return self.name
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message='Language already exists(case insensitive match).'
            )
        ]

class Book(models.Model):
    '''Model representing a book (but not a specific copy of a book)'''
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT, null=True)
    '''ForeignKey is used because a book can only have one author but authors can have
    multiple books.
    Author as a string rather than object because it hasn't been declared yet
    in file'''

    summary = models.TextField( max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 characters <a href="www.isbn-internation.org/content/what-isbn">ISBN number</a>')

    ''' ManyToManyField used because genre can contain many books. Books can cover many genres
    Genre class has already been defined so we can specify the object above'''
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL,null=True)
    cover = models.ImageField(upload_to='media',height_field=None, width_field=None,max_length=200 ,null=True, blank=True)

    def __str__(self):
        """String for representing the Model object"""
        return self.title
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book"""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        '''Function to display genres'''
        return "," .join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
    
import uuid

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. 
    that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across the whole library")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o','On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability'
    )

    @property
    def is_due(self):
        return bool( (self.due_back and date.today) > self.due_back)
   
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    


    

library/locallibrary/catalog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class SignUpUserForm(UserCreationForm):
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1','password2')

    def __init__(self, *args, **kwargs):
        super(SignUpUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

library/locallibrary/catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Book, Author, BookInstance, Genre, Language
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from catalog.forms import SignUpUserForm

class RegisterUserView(generic.CreateView):
    form_class=SignUpUserForm
    success_url=reverse_lazy('login')
    template_name='registration/signup.html'
    

def index(request):

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    num_authors = Author.objects.all().count()

    context= {
        'num_books': num_books,
        'num_authors': num_authors,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available
    }

    return render(request, 'catalog/index.html', context=context)

class BookListView(generic.ListView):
    model = Book

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

library/locallibrary/catalog/templates/catalog/author_detail.html
{% extends 'catalog/base_generic.html' %}
{%block title %}
<title> {{ author.first_name }}, {{ author.last_name }}</title>
{% endblock %}
{% block content %}

<p><strong>Name: </strong>  {{ author.first_name }}, {{ author.last_name }}</p>
    <p><strong>Date of Birth: </strong> {{ author.date_of_birth }}</p>
    {% if author.date_of_death %}
<p><strong>Died: </strong> {{ author.date_of_death }}</p>
{% endif %}

{% endblock %}

library/locallibrary/catalog/templates/catalog/author_list.html
{% extends 'catalog/base_generic.html' %}

{%block title %}
<title> Author List</title>
{% endblock %}
{% block content%}
<h1>Author List</h1>
<div style="display: block; ">
    <table style="text-align: start;">
        <tr>
            <th>No.</th>
            <th>Author</th>
        </tr>
        {% for author in author_list %} 
        <tr>

            <td style="width: 50px;"><em>{{author.pk}}</em></td>
            <td><a href="{% url 'author-detail' pk=author.pk %}"> {{ author.first_name }}, {{ author.last_name }}</a></td>
        </tr>

        {% endfor %}
    </table>
    {% for author in author_list %}
    <!--<p><strong>Name: </strong> <a href="{% url 'author-detail' pk=author.pk %}"> {{ author.first_name }}, {{ author.last_name }}</a></p>
-->
    




    {% endfor %}
</div>

{% endblock %}

library/locallibrary/catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Local Library</title>
    {% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- 
    
  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    <div class="heading" style="z-index: 999;background-color: rgb(13, 194, 58);padding: 20px; font: 'Lobster' cursive; position: sticky;top: 0;">
        <header>
            <a href=""><h1 class="heading">Najib's Local Library</h1></a>
            
        </header>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        {% if user.is_authenticated %}
                        <li>User: {{ user.get_username}}</li>
                        <li>
                            <form action="{% url 'logout' %}" id="logout-form" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link">Logout</button>
                            </form>
                        </li>
                        {% else %}
                        <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
                        {% endif %}
                        <li><a href="{% url 'index' %}"> Home </a></li>
                        <li><a href="{% url 'books' %}">All books</a></li>
                        <li><a href="{% url 'authors' %}">All authors</a></li>
                    </ul>
                    {% endblock %}

            </div>
            <div class="col-sm-10">
              
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    
    

</body>
</html>

library/locallibrary/catalog/templates/catalog/book_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<h1>
    Title: {{ book.title }}
</h1>
<p><strong>Author: </strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a> </p>
<p><strong>Summary: </strong>{{ book.summary }}</p>
<p><strong>ISBN: </strong>{{ book.isbn }}</p>
<p><strong>Language: </strong>{{ book.language }}</p>
<p><strong>Genre: </strong>{{ book.genre.all|join:", " }}</p>

<div style="margin-left: 20px; margin-top: 20px;">
    <h4>Copies</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr />
    <p
    class="{% if copy.status == 'a'%}text-success{% elif copy.status == 'm' %} text-danger {% else %} text-warning{% endif %}">
    {{ copy.get_status_display }}
    </p>
    {% load static %}
    {% if copy.status != 'a' and copy.status != 'r' %}
    <p><strong>Due to be returned: </strong> {{ copy.due_back }}</p>
    {% endif %}
    
    <p><strong>Imprint: </strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id: </strong> {{ copy.id }}</p>
    {% endfor %}
</div>

{% endblock %}

library/locallibrary/catalog/templates/catalog/book_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>({{ book.author}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>

{% endif %}
{% endblock %}

library/locallibrary/catalog/templates/catalog/index.html
{% extends 'catalog/base_generic.html' %}

{% block title %}
<title>Library Home</title>
{% endblock %}

{% block content %}
<h1 class="heading">Local Library Home</h1>
<p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>
</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies Available:</strong> {{ num_instances_available}}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>
{% endblock %}